import { AlertTriangle, Sparkles } from "lucide-react";
import { formatRelativeTime } from "../utils/time";
import { T, sans } from "../styles/tokens";

/*
  Footer explaining where an analysis result came from, so model output
  and sample data are never mistaken for each other.
  `meta` is the module record's provenance: { source, model, generatedAt,
  documents, usage, warnings, note }.
*/
export default function Provenance({ meta }) {
  if (!meta) return null;
  const sample = meta.source !== "model";
  const docs = meta.documents?.length ?? 0;

  return (
    <div className="mt-6 pt-3 border-t" style={{ borderColor: T.line }}>
      <div className="flex items-start gap-1.5">
        {sample
          ? <AlertTriangle size={12} className="mt-[2px] shrink-0" style={{ color: T.warn }} aria-hidden="true" />
          : <Sparkles size={12} className="mt-[2px] shrink-0" style={{ color: T.inkSoft }} aria-hidden="true" />}
        <p className="text-[11px] leading-relaxed" style={{ ...sans, color: T.black, opacity: 0.6 }}>
          {sample ? (
            <>
              <span style={{ color: T.warn, opacity: 1 }}>Sample result.</span>{" "}
              {meta.note ?? "This is illustrative data, not an analysis of your documents."}
            </>
          ) : (
            <>
              Generated by {meta.model ?? "the model"} from {docs} document{docs === 1 ? "" : "s"}
              {meta.chunksTotal ? ` (${meta.chunksUsed} of ${meta.chunksTotal} passages)` : ""}
              {meta.generatedAt ? ` · ${formatRelativeTime(meta.generatedAt)}` : ""}.
              {" "}Interpretations are the model's; quoted evidence comes from your documents.
            </>
          )}
        </p>
      </div>
      {!sample && meta.warnings?.length > 0 && meta.warnings.map((w, i) => (
        <p key={i} className="text-[11px] mt-1 ml-[18px]" style={{ ...sans, color: T.warn }}>{w}</p>
      ))}
    </div>
  );
}
